version: '3.7'

services:
  keycloak:
    container_name: docker_keycloak
    image: quay.io/keycloak/keycloak:23.0.6
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KC_HTTP_ENABLED: true
      KC_HEALTH_ENABLED: true
      KC_LOG_LEVEL: info
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - 8080:8080
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    volumes:
      - ./realm.json:/opt/keycloak/data/import/realm.json:ro
  
  auth_service:
    build: ./auth_service
    container_name: go_auth_container
    environment:
      - GO_ENV=dev
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      - keycloak
